### PR TITLE
V3.000 mastered

### PR DESCRIPTION
**Pull request by m4rc1e**
Hello,

@Fonthausen, @crystaltype and myself have upgraded Varela Round.

My commit message doesn't do justice how much work has been done to the family. The glyph count has gone from 294 to 793 glyphs.

screen shot 2016-10-05 at 22 02 30

Kind regards,
Marc Foley

### CODE REVIEW

**Comment by avrahamcornfeld** [comment]
Looking good! Great work!

**Comment by jurej** [comment]
Thank you guys! Amazing work! Very greatful!

**Comment by jurej** [comment]
Hey guys! Is this one going to get merged?

**Comment by avrahamcornfeld** [comment]
​Yes..
Forgot I have to press the button :)
​

 _א_
avrahamcornfeld.com
alefalefalef.co.il

**Pull request merged**
